### ISSUE TITLE
Consider renaming? Pre-existing software from Scionics

### ISSUE THREAD

**Issue by CBroz1** [pyratlib/pyrat#1]
This is an exciting project, and I look forward to seeing where it goes, but I landed here by mistake looking for the [proprietary colony management software from Scionics](https://www.scionics.com/pyrat.html). Scionics is a German company founded in 2006.

**Comment by pyratlib** [comment]
Hi Crhis,

Thank you for the contact. We didn't know about this project from Scions. We are an open access python library and we have no commercial intention with our project. This acronym is widely used in python libraries, pypi has several registered. Our registry is like Pyratlib. Anything we are available.

Regards

De: Chris Brozdowski ***@***.***>
Enviada em: quarta-feira, 22 de dezembro de 2021 17:42
Para: pyratlib/pyrat ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: [pyratlib/pyrat] Consider renaming? Pre-existing software from Scionics (Issue #1)


This is an exciting project, and I look forward to seeing where it goes, but I landed here by mistake looking for the proprietary colony management software from Scionics<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.scionics.com%2Fpyrat.html&data=04%7C01%7C%7Caf4c9bacac924a9fca8408d9c58b8cc5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637758025423710556%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=guFKCJHXkbkqhKBgXUYVVm24SqWZC%2FuUvEwoDItiu%2F4%3D&reserved=0>. Scionics is a German company founded in 2006.

-
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpyratlib%2Fpyrat%2Fissues%2F1&data=04%7C01%7C%7Caf4c9bacac924a9fca8408d9c58b8cc5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637758025423720548%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wnCfRnQG4GpYmM9zV%2FTlVcrtvqZSB0Cjp%2FTsBlzzbL8%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATOOTFYAL5OYQZWOJQQI7R3USIZ2TANCNFSM5KTLFOAQ&data=04%7C01%7C%7Caf4c9bacac924a9fca8408d9c58b8cc5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637758025423730542%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LOgJA4uSXBnir8%2BadAoWgwcabWu8Ot3U%2FOMsdqE1aQM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Caf4c9bacac924a9fca8408d9c58b8cc5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637758025423730542%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cxT%2B69WcwoOJByaphuA9fHBLWNUAm2oTB75z9Ow0IGw%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Caf4c9bacac924a9fca8408d9c58b8cc5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637758025423740538%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XdwxjjRdFchjLHJHd9vor8btaUDqa5ZAXsDJ554XVCY%3D&reserved=0>.
