### ISSUE TITLE
Group TSNE

### ISSUE THREAD

**Issue by kcrisco22** [pyratlib/pyrat#2]
Hello thank you for PyRat I have it working.  I am trying to understand the behavioral classification aspect of PyRat. I can run an individual video/file and get the classification and t-sne output. However what I want to be able to do is input all my videos and get behavior clusters represented across all of them and then break these down by animal. In addition, is there a way to get the output of the frames as a csv? And see how long the behavioral clip is? Thank you!

**Comment by tuliofalmeida** [comment]
Hi ! Thanks for using PyRAT. You have a very interesting question. First, could you explain better the conditions of your videos? How many videos, durantion, how many animals. In this sense, we can think of the best way to approach it. I believe that saving this information in a csv is possible.

**Comment by kcrisco22** [comment]
Awesome thank you for your response. They are Force Swim videos I have 40 videos recorded at 30fps. 1 animal / video. I want to be able to get output 1 set of clustered behaviors and then analyze them individually--similar to BSOID or VAME. Let me know if that makes sense or if you need any more info.

**Comment by tuliofalmeida** [comment]
OK. We are going to do some tests and update the library to analyze the videos this way.
One more thing, if you are using colab it may not be able to process all the videos at once. But we'll discuss it later, okay?

**Comment by kcrisco22** [comment]
I was just trying it out in Collab. But I can run it in Spyder and we have
a gpu available if necessary. Thank you!

**Comment by tuliofalmeida** [comment]
Hey! We made changes to the code for you to test the classification of multiple videos. I made a colab with an example using any data. I hope it works, if it doesn't work or you have some other problem please post here.

https://github.com/pyratlib/pyrat/blob/main/Classify_Multiple_Videos.ipynb

**Comment by tuliofalmeida** [comment]
Hi @kcrisco22, I don't know if you had time to test the functions, but I will close the topic for a while. If you have any problems, just reopen it. Thanks.
