### ISSUE TITLE
cluster number

### ISSUE THREAD

**Issue by Wulin-Tan** [pyratlib/pyrat#3]
Hi, pyrat is perfect for my project. 
And the default clusters are too many for my video. How can I adjust the number of clusters when I run the rat.ClassifyBehavior?
Thank you.

**Comment by tuliofalmeida** [comment]
Hi, that's great! 
For you to adjust the number of clusters in your video, you need to increase the `distance` variable in the `rat.ClassifyBehavior` function. The adjustment of this metric is done by trial and error. There are some techniques to help this process and we will develop a tutorial to facilitate this process! Your issue will remain open in the meantime and I'll notify you as soon as we're done.
