### ISSUE TITLE
pyrat clustering applied to multiple animals or videos

### ISSUE THREAD

**Issue by Wulin-Tan** [pyratlib/pyrat#4]
Hi, pyrat developers:
How do I apply pyrat clustering to multiple animals/videos? (assuming one video per animal)
thank you.
Wulin

**Comment by tuliofalmeida** [comment]
Hey, yes!
Did you checked this notebook? Or does this not solve your question?
https://github.com/pyratlib/pyrat/blob/main/Classify_Multiple_Videos.ipynb

**Comment by Wulin-Tan** [comment]
@tuliofalmeida 
just got the notebook. Thanks. That helps a lot.

**Comment by tuliofalmeida** [comment]
Thank you, I'll close the issue if you have other questions just open it again!
